// Generated by CoffeeScript 1.4.0
(function() {
  var html_minifier, os, render_views, url;

  os = require('os');

  url = require('url');

  html_minifier = require('html-minifier');

  render_views = function(req, res, body_view, code) {
    var complete, query, response;
    if (code == null) {
      code = 200;
    }
    complete = function(arg) {
      var response;
      response = arg.response;
      code = arg.code;
      if (query.hasOwnProperty('ajaxify')) {
        return res.send(html_minifier.minify(response.body, {
          collapseWhitespace: true,
          removeComments: true
        }, code));
      } else {
        if (response.header !== '' && response.body !== '' && response.footer !== '') {
          return res.send(html_minifier.minify(response.header + response.body + response.footer, {
            collapseWhitespace: true,
            removeComments: true
          }, code));
        }
      }
    };
    query = url.parse(req.url, true).query;
    response = {
      header: '',
      body: '',
      footer: ''
    };
    if (query.hasOwnProperty('ajaxify')) {
      code = 200;
      return res.render(body_view, {}, function(err, html) {
        response.body = html;
        return complete({
          response: response,
          code: code
        });
      });
    } else {
      res.render(body_view, {}, function(err, html) {
        response.body = html;
        return complete({
          response: response,
          code: code
        });
      });
      res.render('view_header', {}, function(err, html) {
        response.header = html;
        return complete({
          response: response,
          code: code
        });
      });
      return res.render('view_footer', {}, function(err, html) {
        response.footer = html;
        return complete({
          response: response,
          code: code
        });
      });
    }
  };

  exports.index = function(req, res) {
    return render_views(req, res, 'view_index');
  };

  exports.features = function(req, res) {
    return render_views(req, res, 'view_features');
  };

  exports.about = function(req, res) {
    return render_views(req, res, 'view_about');
  };

  exports.blog = function(req, res) {
    return render_views(req, res, 'view_blog');
  };

  exports.contact = function(req, res) {
    return render_views(req, res, 'view_contact');
  };

  exports.error = function(req, res) {
    return render_views(req, res, 'view_404', 404);
  };

}).call(this);
